# -*- coding: utf-8 -*-
"""Adaptive RAG Agent System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZzWq5zzLk8xjUP-dMSxyHny2hm9fvQ7

https://colab.research.google.com/drive/1cZzWq5zzLk8xjUP-dMSxyHny2hm9fvQ7#scrollTo=meWGXcJdyN44
"""

# !pip install langchain-core

# !pip install langchain-community

# !pip install langchain-huggingface

!pip install langchain-classic

!pip install langchain-ollama langchain-core

!pip install langchain-text-splitters

!pip install -qU langchain-text-splitters

!pip install chromadb

!pip install langchain-groq

from langchain_groq import ChatGroq

from langchain_core.prompts import PromptTemplate
# from langchain_community.chat_models import ChatGroq

from langchain_core.output_parsers import JsonOutputParser, StrOutputParser

from langchain_classic import hub
from langchain_ollama.llms import OllamaLLM
import ollama
from langchain_community.embeddings import OllamaEmbeddings

from sentence_transformers import SentenceTransformer
from langchain_community.embeddings import HuggingFaceEmbeddings
hf = HuggingFaceEmbeddings(
    model_name='all-MiniLM-L12-v2'
)

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import TextLoader
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import GPT4AllEmbeddings

from google.colab import drive
drive.mount('/content/drive')

text = ['./data_dictionary.txt',
        './data_summary.txt',
        './shap_summary.txt']

docs = [TextLoader(url).load() for url in text]
docs_list = [item for sublist in docs for item in sublist]

text_splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
    chunk_size=400, chunk_overlap=100
)
doc_splits = text_splitter.split_documents(docs_list)

# Add to vectorDB
vectorstore = Chroma.from_documents(
    documents=doc_splits,
    collection_name="churn-rag-chroma-2",
    embedding=hf,

)

"""First we will create a Business Analyst and Data Science Manager to reports from the model. This is simple agents created by Prompt defention and simple RAG.

Multiple questions are asked to the business analyst agent and then the answers for these questions are passed as context to Data Science Manger
"""

from langchain_groq import ChatGroq

# Post-processing
def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

def business_analyst1(question, model, top_k=7, fetch_k=20, retriver_type="normal", search_type="similarity"):

    prompt = PromptTemplate(
        template=""" You are a business analyst for a telecom company.
        Your job is to answer question from executives on Churn.
        Answer ONLY with stats you got from the context provided.

        Context: {context}

        Question: {question}""",
        input_variables=["question", "context"],
    )

    retriever1 = vectorstore.as_retriever(search_kwargs={'k': top_k})
    docs = retriever1.invoke(question)

    document = format_docs(docs)

    llm0 = ChatGroq(
        model="llama-3.3-70b-versatile",
        groq_api_key="put_your_api"
    )

    rag_chain0 = prompt | llm0 | StrOutputParser()

    answer = rag_chain0.invoke({
        "question": question,
        "context": document
    })

    return answer



def manager(question,model,output1,output2,output3,output4):

    # Prompt
    prompt = PromptTemplate(
        template=""" You are manager of data science team for a telecom company.
                You get different reports on churn from your business analyst in your team.
                Your job is to format and proof read the report provided to you by the business analyst and create a enriched report for senior executive team within 1000 words.
                The end user might not be tech savvy, so keep the language easy to understand
                Answer should be properly formatted and user friendly and easy to understand.
                class 1 is churn.
                Use the below context for reference to make answer.

                Context: {context}

                Question: {question}""",
        input_variables=["question", "context"],
    )


    llm0 = ChatGroq(
    model="llama-3.3-70b-versatile",
    groq_api_key="put_your_api"
)
    # Chain
    rag_chain0 = prompt | llm0 | StrOutputParser()

    answer = rag_chain0.invoke({"question": question,"context": output1 + "\n" + output2 + "\n" + output3+"\n"+output4})

    return answer

output1=(business_analyst1(question="Look at all features and identify the top 20 features which increases the probability of class 1 the most. The highest increase in probability will be on top",
                        model="llama3:latest",top_k=8,retriver_type='normal'))
print(output1)

output2=(business_analyst1(question="Look at all features and identify the top 10 features which decreases the probability of class 1 the most. The highest decrease in probability will be on top",
                        model="llama3:latest",top_k=8,retriver_type='normal'))
print(output2)

output3=(business_analyst1(question="Look at all features and identify the top 10 features importance rank in the model prediction. The lowest importance rank in the model prediction be on top",
                        model="llama3:latest",top_k=8,retriver_type='normal'))
print(output3)

output4=(business_analyst1(question="What are the list of different action features?",
                        model="llama3:latest",top_k=3,retriver_type='normal'))
print(output4)

final_report=manager(question=f"""What are the top 5 reasons for churn?\n
                             What are top 5 recommended actions to improve retention and decrease churn?""",
                             output1=output1,
                             output2=output2,
                             output3=output3,
                             output4=output4,
                             model="llama3:latest")
print(final_report)

response2=manager(question=f"""
                             What are top 5 recommended actions to improve retention and decrease churn specifically using action features?
                             Only use action features for this recommnedation""",
                             output1=output1,
                             output2=output2,
                             output3=output3,
                             output4=output4,
                             model="llama3:latest")
print(response2)

"""### LangGraph Agents
What are LangGraph Agents?
In the LangChain and LangGraph context, an agent is a sophisticated construct that utilizes language models (LLMs) to reason and decide on actions in an autonomous manner. Unlike traditional LangChain chains that follow a predefined sequence, agents dynamically determine their next steps based on the current situation and goals.
Building Agents with LangGraph
Define Nodes: Each node in the LangGraph represents a function or a LangChain runnable (like an LLMChain).

Connect with Edges: Define edges to dictate the flow of information and control between nodes. You'll often have conditional edges where the next node is determined based on the output of the current node.

Agent Logic: One or more nodes will typically contain the agent's decision-making logic, using an LLM to analyze the current state and choose the next action.
We will try to implement an advanced RAG system for the above Task which will be more accurate. We will design this system as LangGraph agents. We will add the Business Analysts and Manager Agents into this architecture
"""

from langchain_core.prompts import PromptTemplate
from langchain_groq import ChatGroq
from langchain_core.output_parsers import JsonOutputParser

from langchain_classic import hub
from langchain_core.output_parsers import StrOutputParser
from typing_extensions import TypedDict
from typing import List
from langchain_core.documents import Document
from langgraph.graph import END, StateGraph
from pprint import pprint

import os
os.environ["GROQ_API_KEY"] = "put_your_api"

from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser, StrOutputParser
from langchain_groq import ChatGroq

# Fast LLM for grading
llm_fast = ChatGroq(
    model="llama-3.1-8b-instant",
    temperature=0
)

# Smart LLM for report generation
llm_smart = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0
)

retrieval_prompt = PromptTemplate(
    template="""You are a grader assessing relevance of a retrieved document to a user question.

Here is the retrieved document:
{document}

Here is the user question:
{question}

If the document contains keywords related to the user question, grade it as relevant.

Give a binary score 'yes' or 'no'.

Return JSON format:
{{"score":"yes"}} or {{"score":"no"}}
""",
    input_variables=["question", "document"],
)

retrieval_grader = retrieval_prompt | llm_fast | JsonOutputParser()

buisiness_analyst_prompt = PromptTemplate(
    template="""You are a business analyst for a telecom company.

Your job is to create a report for senior executives on questions asked.

Answer ONLY with stats you got from the context provided.
DO NOT add any erroneous stats.

Context:
{context}

Question:
{question}
""",
    input_variables=["question", "context"],
)

business_analyst_rag_chain = buisiness_analyst_prompt | llm_smart | StrOutputParser()

manager_prompt = PromptTemplate(
    template="""You are manager of a data science team for a telecom company.

You receive multiple reports from business analysts.

Your job is to:

• Combine the reports
• Proofread them
• Create a clear executive summary

The final report must:
- be easy to understand
- be properly formatted
- avoid technical jargon

Note: class 1 represents churn.

Context:
{context}

Question:
{question}
""",
    input_variables=["question", "context"],
)

manager_rag_chain = manager_prompt | llm_smart | StrOutputParser()

hallucination_prompt = PromptTemplate(
    template="""You are a grader assessing whether an answer is grounded in facts.

Facts:
{documents}

Answer:
{generation}

Return a binary score 'yes' or 'no'.

Return JSON format:
{{"score":"yes"}} or {{"score":"no"}}
""",
    input_variables=["generation", "documents"],
)

hallucination_grader = hallucination_prompt | llm_fast | JsonOutputParser()

answer_grader_prompt = PromptTemplate(
    template="""You are grading whether an answer properly resolves a question.

Answer:
{generation}

Question:
{question}

Return a binary score 'yes' or 'no'.

Return JSON format:
{{"score":"yes"}} or {{"score":"no"}}
""",
    input_variables=["generation", "question"],
)

answer_grader = answer_grader_prompt | llm_fast | JsonOutputParser()

re_write_prompt = PromptTemplate(
    template="""You are a question rewriter.

Your job is to rewrite a question so it becomes optimized for vector database retrieval.

Original question:
{question}

Return ONLY the improved question.
Do not add any explanation.
""",
    input_variables=["question"],
)

question_rewriter = re_write_prompt | llm_fast | StrOutputParser()

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 20}
)

question = "Which features increase churn probability the most?"

docs = retriever.invoke(question)

filtered_docs = []

for d in docs:
    score = retrieval_grader.invoke({
        "question": question,
        "document": d.page_content
    })

    if score["score"] == "yes":
        filtered_docs.append(d)

context = format_docs(filtered_docs)

# Generate analyst report
answer = business_analyst_rag_chain.invoke({
    "question": question,
    "context": context
})

print(answer)

class GraphState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        question: question
        generation: LLM generation
        documents: list of documents
        report: FInal report from Manager LLM
    """
    question : str
    generation : str
    documents : List[str]
    report : str

### Nodes
def retrieve(state):
    """
    Retrieve documents

    Args:
        state (dict): The current graph state

    Returns:
        state (dict): New key added to state, documents, that contains retrieved documents
    """
    print("---RETRIEVE---")
    question = state["question"]

    # Retrieval
    documents = retriever.invoke(question)
    return {"documents": documents, "question": question}

def analyst_generate(state):
    """
    Generate answer

    Args:
        state (dict): The current graph state

    Returns:
        state (dict): New key added to state, generation, that contains LLM generation
    """
    print("---GENERATE---")
    question = state["question"]
    documents = state["documents"]
    context=format_docs(documents)

    # RAG generation
    generation = business_analyst_rag_chain.invoke({"context": context, "question": question})
    return {"documents": documents, "question": question, "generation": generation}

def grade_documents(state):
    """
    Determines whether the retrieved documents are relevant to the question.

    Args:
        state (dict): The current graph state

    Returns:
        state (dict): Updates documents key with only filtered relevant documents
    """

    print("---CHECK DOCUMENT RELEVANCE TO QUESTION---")
    question = state["question"]
    documents = state["documents"]

    # Score each doc
    filtered_docs = []
    for d in documents:
        score = retrieval_grader.invoke({"question": question, "document": d.page_content})
        grade = score['score']
        if grade == "yes":
            print("---GRADE: DOCUMENT RELEVANT---")
            filtered_docs.append(d)
        else:
            print("---GRADE: DOCUMENT NOT RELEVANT---")
            continue
    return {"documents": filtered_docs, "question": question}

def transform_query(state):
    """
    Transform the query to produce a better question.

    Args:
        state (dict): The current graph state

    Returns:
        state (dict): Updates question key with a re-phrased question
    """

    print("---TRANSFORM QUERY---")
    question = state["question"]
    documents = state["documents"]

    # Re-write question
    better_question = question_rewriter.invoke({"question": question})
    return {"documents": documents, "question": better_question}


def decide_to_generate(state):
    """
    Determines whether to generate an answer, or re-generate a question.

    Args:
        state (dict): The current graph state

    Returns:
        str: Binary decision for next node to call
    """

    print("---ASSESS GRADED DOCUMENTS---")
    question = state["question"]
    filtered_documents = state["documents"]

    if not filtered_documents:
        # All documents have been filtered check_relevance
        # We will re-generate a new query
        print("---DECISION: ALL DOCUMENTS ARE NOT RELEVANT TO QUESTION, TRANSFORM QUERY---")
        return "transform_query"
    else:
        # We have relevant documents, so generate answer
        print("---DECISION: GENERATE---")
        return "analyst_generate"

def grade_generation_v_documents_and_question(state):
    """
    Determines whether the generation is grounded in the document and answers question.

    Args:
        state (dict): The current graph state

    Returns:
        str: Decision for next node to call
    """

    print("---CHECK HALLUCINATIONS---")
    question = state["question"]
    documents = state["documents"]
    generation = state["generation"]

    score = hallucination_grader.invoke({"documents": format_docs(documents), "generation": generation})
    grade = score['score']

    # Check hallucination
    if grade == "yes":
        print("---DECISION: GENERATION IS GROUNDED IN DOCUMENTS---")
        # Check question-answering
        print("---GRADE GENERATION vs QUESTION---")
        score = answer_grader.invoke({"question": question,"generation": generation})
        grade = score['score']
        if grade == "yes":
            print("---DECISION: GENERATION ADDRESSES QUESTION---")
            return "useful"
        else:
            print("---DECISION: GENERATION DOES NOT ADDRESS QUESTION---")
            return "not useful"
    else:
        pprint("---DECISION: GENERATION IS NOT GROUNDED IN DOCUMENTS, RE-TRY---")
        return "not supported"

def manager_generate(state):
    """
    Generate answer

    Args:
        state (dict): The current graph state

    Returns:
        state (dict): New key added to state, generation, that contains LLM generation
    """
    print("---GENERATE---")
    question = state["question"]
    context=state["generation"]

    # RAG generation
    report = manager_rag_chain.invoke({"context": context, "question": question})
    return {"question": question, "report": report}

## Create the Graph Agent

workflow = StateGraph(GraphState)

# Define the nodes
workflow.add_node("retrieve", retrieve) # retrieve
workflow.add_node("grade_documents", grade_documents) # grade documents
workflow.add_node("analyst_generate", analyst_generate) # generatae
workflow.add_node("transform_query", transform_query) # transform_query
workflow.add_node("manager_generate", manager_generate) # manager_query

# Build graph
workflow.set_entry_point("retrieve")
workflow.add_edge("retrieve", "grade_documents")
workflow.add_conditional_edges(
    "grade_documents",
    decide_to_generate,
    {
        "transform_query": "transform_query",
        "analyst_generate": "analyst_generate",
    },
)
workflow.add_edge("transform_query", "retrieve")
workflow.add_conditional_edges(
    "analyst_generate",
    grade_generation_v_documents_and_question,
    {
        "not supported": "analyst_generate",
        "useful": "manager_generate",
        "not useful": "transform_query",
    },
)
workflow.add_edge("manager_generate",END)

# Compile
app = workflow.compile()

##Test the Agent with a Question

# Run
inputs = {"question": "What are the top reasons which increases the probability of class 1?"}
for output in app.stream(inputs):
    for key, value in output.items():
        # Node
        pprint(f"Node '{key}':")
    pprint("\n---\n")

# Final generation
pprint(value["report"])

inputs = {"question": "What are 5 recommended actions to increase retention or to reduce churn?"}
for output in app.stream(inputs):
    for key, value in output.items():
        # Node
        pprint(f"Node '{key}':")
    pprint("\n---\n")

# Final generation
pprint(value["report"])

